os: linux
dist: trusty
sudo: required
language: cpp
services:
- docker
if: tag IS blank
env:
  global:
  - PLAT=x86_64
  - TRAVIS_TAG=linux
before_script:
- docker pull rayproject/ray_arrow_manylinux1_x86_64_base:llvm
script:
- git clone https://github.com/ray-project/arrow
- git -C arrow checkout 007e1ca289e979bac80231fa9ee7510be744b60b
- mkdir -p dist
- pushd arrow/python/manylinux1
- docker run --shm-size=2g -e SETUPTOOLS_SCM_PRETEND_VERSION=0.12.0-RAY -e PYTHON_VERSIONS="2.7,16
  2.7,32 3.5,16 3.6,16 3.7,16" -e WHEEL_VERSION=0.31.1 -v $PWD:/io -v $PWD/../../:/arrow
  rayproject/ray_arrow_manylinux1_x86_64_base:llvm /io/build_arrow.sh
- popd
- sudo mv arrow/python/manylinux1/dist/* dist/
deploy:
  provider: s3
  access_key_id: AKIAJNTVCMLWEWZOOZGQ
  secret_access_key:
    secure: ry5YAQQSyEtvg37Rpo36UENEc1c8KKoVDfIz2tjbemC59+0dGVev4Bt4WFO4QEcN2WHWmk0FdJwl9HtagZut5aHtkVcBxtUkFiW8SR21KdlMFXanO0ZtY7VfS2TZfevLK5vVXeeFeUFnJ8962G5t0zy5ufAFCygHr50VQkN4usOR3nbQAtbjlvrsVh1LCbiMHEoewsZ7uo+LqmyQ9yc08OmdfKTFszOdYSLqJN4H+wyJssrN40LPTziATTaIrSiHRHPqLrzQIDJ9+/rY4TL+hSXGMvjOCrkLNLEFPfWlTVdbkGAaZhAM4l6e1ZR6Xj1JBxvnkaCt+X02GTE8kBDxAQA9yUgsQNhukBfJBpZW9ep/VapmMrtDMcOAoX+YUA7MpJWDc3BVy/4l/KV52fpViEv9sLVFUlqvDw7ZUB7+KDKByrRDQa/cBlufZ/z79Wxnce7DynKEenXgiP/IXSK4IHK9/R8jfyPnwtcYOEnDzq5WHAWqZNXMxQXGAMSo+MWsc0AqNZqPDlhdUZUXrkXeAdRvEnFo97t6O/O3sczxFJUflgMnLwlOlQ+UZ6nm/YJh4Bgt2FmOKpYSJrOF5pao5wHs0C8VNDg/v2Fyn+zKkuPRM4oynUydfGmSkevQRTXuciB8uvFfqtPqZnoFpA2SECiUzPSqNPeQUP+lOiEy2BA=
  bucket: arrow-wheels
  local-dir: dist
  upload-dir: $TRAVIS_COMMIT
  acl: public_read
  on:
    repo: pcmoritz/arrow-build
notifications:
  email:
  - pcmoritz@gmail.com
