sudo: required

matrix:
  include:

    - os: linux
      dist: trusty
      language: cpp
      services:
        - docker
      if: tag IS blank
      env:
        global:
          - PLAT=x86_64
          - TRAVIS_TAG=linux
      before_script:
        - docker pull rayproject/ray_arrow_manylinux1_x86_64_base:llvm
      script:
        - git clone https://github.com/ray-project/arrow
        - git -C arrow checkout 007e1ca289e979bac80231fa9ee7510be744b60b
        - mkdir -p dist
        - pushd arrow/python/manylinux1
        - docker run --shm-size=2g -e SETUPTOOLS_SCM_PRETEND_VERSION=0.12.0-RAY -e PYTHON_VERSIONS="2.7,16 2.7,32 3.5,16 3.6,16 3.7,16" -e WHEEL_VERSION=0.31.1 -v $PWD:/io -v $PWD/../../:/arrow rayproject/ray_arrow_manylinux1_x86_64_base:llvm /io/build_arrow.sh
        - popd
        - sudo mv arrow/python/manylinux1/dist/* dist/

    - os: osx
      osx_image: xcode8.3
      language: generic
      if: tag IS blank
      env:
        global:
          - PLAT=x86_64
          - TRAVIS_TAG=macos
          - MACOSX_DEPLOYMENT_TARGET="10.9"
          - PYARROW_BUILD_VERBOSE=1
      before_install:
        - git clone https://github.com/matthew-brett/multibuild # TODO pin it
        - git -C multibuild checkout 4e7a9396e9a50731bb83fc0d16bb98fb0c4032d7

        - git clone https://github.com/ray-project/arrow
        - git -C arrow checkout 007e1ca289e979bac80231fa9ee7510be744b60b

        # Also remove artifacts that depend on Boost
        - brew uninstall boost cgal postgis sfcgal
        - brew update
        - brew upgrade cmake
        - brew install bison flex

        - export CONFIG_PATH=`pwd`/arrow/dev/tasks/python-wheels/osx-build.sh
        - source multibuild/common_utils.sh
        - source multibuild/travis_osx_steps.sh

      install:
        - mkdir -p dist

        # multibuild's default clean_code function
        - clean_code arrow 007e1ca289e979bac80231fa9ee7510be744b60b

        # the following functions are defined in osx-build.sh
        - build_wheel arrow
        - install_run arrow

        # move built wheels to a top level directory
        - mv -v arrow/python/dist/* dist/

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  bucket: arrow-wheels
  skip_cleanup: true
  region: us-west-2
  local-dir: dist/
  upload-dir: $TRAVIS_COMMIT
  on:
    repo: pcmoritz/arrow-build
notifications:
  email:
  - pcmoritz@gmail.com
